version: '3.8'

services:
  master:
    image: mysql:8
    container_name: bdl-master
    environment:
      MYSQL_ROOT_PASSWORD: telurrebus
      MYSQL_DATABASE: appku
      MYSQL_USER: bang_kopi
      MYSQL_PASSWORD: telurrebus
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-do-db=appku
      --binlog_format=ROW
      --gtid_mode=ON
      --enforce-gtid-consistency=ON
      --mysql-native-password=ON
    ports:
      - "3307:3306"
    networks:
      - appku-net
    volumes:
      - ./custom.cnf:/etc/mysql/conf.d/mysql.cnf

  slave1:
    image: mysql:8
    container_name: bdl-slave1
    environment:
      MYSQL_ROOT_PASSWORD: telurrebus
      MYSQL_DATABASE: appku
      MYSQL_USER: bang_kopi
      MYSQL_PASSWORD: telurrebus
    command: >
      --server-id=2
      --relay-log=mysql-relay-bin
      --log-bin=mysql-bin
      --read-only=ON
      --gtid_mode=ON
      --enforce-gtid-consistency=ON
      --mysql-native-password=ON
    ports:
      - "3308:3306"
    depends_on:
      - master
    networks:
      - appku-net
    volumes:
      - ./custom.cnf:/etc/mysql/conf.d/mysql.cnf
  slave2:
    image: mysql:8
    container_name: bdl-slave2
    environment:
      MYSQL_ROOT_PASSWORD: telurrebus
      MYSQL_DATABASE: appku
      MYSQL_USER: bang_kopi
      MYSQL_PASSWORD: telurrebus
    command: >
      --server-id=3
      --relay-log=mysql-relay-bin
      --log-bin=mysql-bin
      --read-only=ON
      --gtid_mode=ON
      --enforce-gtid-consistency=ON
      --mysql-native-password=ON
    ports:
      - "3309:3306"
    depends_on:
      - master
    networks:
      - appku-net
    volumes:
      - ./custom.cnf:/etc/mysql/conf.d/mysql.cnf

networks:
  appku-net:

